---
abstract: ~
author:
  - 'Shawn M Moore C<code@sartak.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-SARTAK
no_index:
  directory:
    - inc
requires:
  App::Ack: 0
  App::ForkProve: 0
  App::Nopaste: 0
  CPAN::Uploader: 0
  Carp::Always::Color: 0
  Chart::Clicker: 0
  DBD::SQLite: 0
  Data::Dump::Streamer: 0
  Data::Hash::Totals: 0
  Devel::Cover: 0
  Devel::NYTProf: 0
  Devel::StackTrace::WithLexicals: 0
  Dist::Zilla: 0
  Dist::Zilla::PluginBundle::DOY: 0
  ExtUtils::MakeMaker::Dist::Zilla::Develop: 0
  File::Rename: 0
  File::ShareDir: 0
  Getopt::Whatever: 0
  Git::Status::Tackle: 0
  IO::All: 0
  IO::Pty: 0
  IPC::System::Simple: 0
  Lingua::JA::Heisig: 0
  Lingua::JA::Moji: 0
  Lingua::JA::Romanize::Japanese: 0
  Lingua::JP::Kanjidic: 0
  Module::Install: 0
  Module::Install::AutoManifest: 0
  Module::Install::GithubMeta: 0
  Module::Install::ManifestSkip: 0
  Module::Install::ReadmeFromPod: 0
  Module::Versions::Report: 0
  Pod::Cpandoc: 0
  Signal::StackTrace::CarpLike: 0
  Test::NoTabs: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
  Text::MeCab: 0
  Unicode::Tussle: 0
  V: 0
  Web::Scraper: 0
  autovivification: 0
  circular::require: 0
  indirect: 0
  utf8::all: 0
resources:
  homepage: https://github.com/sartak/Task-BeLike-SARTAK/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/Task-BeLike-SARTAK.git
version: 0.05
